### ISSUE TITLE
Feedback UAS

### ISSUE THREAD

**Issue by aufaroot18** [RakhaZaN/uas-frontend#1]
Thank you sudah mengerjakan Final Project UAS. Selamat telah melawan raja terakhir.

Berikut feedback yang bisa kami sampaikan.

## Feedback Umum

- Aplikasi secara umum sudah sesuai Requirement.
- Aplikasi sudah sesuai secara Desain.
- Aplikasi sudah Responsive baik di Desktop dan Mobile.
- Sudah menggunakan Stack yang ditentukan.
- Sudah dibuatkan UI Component beberapa menggunakan Atomic Design.

## Catatan

- Gunakan Layout untuk wrap pages.
- Cool, menggunakan Atomic Design di React.

## Improvement

- Bisa tambahkan state `loading` dan `error` ketika fetch data. [Referensi](https://blog.logrocket.com/modern-api-data-fetching-methods-react/)
- Bisa coba gunakan library fetch seperti `React Query` untuk fetch data.
- Bisa coba tambahkan pagination di Table.
- Bisa coba buat UI Component agar reusable seperti Chakra UI. [Referensi](https://chakra-ui.com/docs/components)

## Thank you.

Terima kasih sudah belajar selama 1 semester, semoga ilmunya bermanfaat. Keep Going.

Sampai jumpa di lain waktu dan kesempatan yang lebih baik.

Regards, Aufa Billah and Asdos. :)

**Comment by rakhazan** [comment]
Terima kasih atas bimbingannya selama 1 semester kak Aufa dan Asdos sekalian. Banyak ilmu baru yang didapatkan.

Terima kasih juga atas review dan feedbacknya yang sangat detail dan sangat membangun.
Untuk sarannya pasti dicoba dan tentunya implementasi pada project project yang akan datang. Masih banyak yang harus diexplore tentang dunia frontend.

# Sekali lagi terima kasih banyak atas ilmunya
